/*

CREATE PROCEDURE cau2
    @MaNV NVARCHAR(20),
    @Nam INT,
    @SLHoaDon INT OUTPUT
AS
BEGIN
    SELECT @SLHoaDon=COUNT(MaHDTT)
    FROM HOADONTT
    WHERE MaNV=@MaNV AND YEAR(NgayLapHD)=@Nam
END

DECLARE @SLHoaDon INT
EXEC cau2 'NV001','2022',@SLHoaDon OUTPUT
SELECT @SLHoaDon


CREATE FUNCTION cau3(@MaBooking nvarchar(20))
RETURNS TABLE
AS
RETURN
(
    SELECT PHIEUDAT.MaBooking, NgayDenDukien, NgayDiDuKien, Kieuphong, SLPhong
FROM PHIEUDAT
    JOIN PHIEUTHUE ON PHIEUDAT.MaBooking=PHIEUTHUE.MaBooking
    JOIN PHONG ON PHIEUTHUE.Maphong=PHONG.Maphong
    JOIN LOAIPHONG ON PHONG.MaLP=LOAIPHONG.MaLP
    JOIN CHITIETPHONGDAT ON PHIEUDAT.MaBooking=CHITIETPHONGDAT.MaBooking
        AND LOAIPHONG.MaLP=CHITIETPHONGDAT.MaLP
WHERE PHIEUDAT.MaBooking=@MaBooking
)

SELECT *
FROM cau3('PD0001')


CREATE VIEW cau5
AS
    SELECT NHANVIEN.MaNV, TenNV, MaHDTT, NgayTT,
        HOADONTT.MaBooking, NgayDenDukien, Tiendatcoc, PHONG.MaLP
    FROM NHANVIEN
        JOIN HOADONTT ON NHANVIEN.MaNV=HOADONTT.MaNV
        JOIN PHIEUDAT ON HOADONTT.MaBooking=PHIEUDAT.MaBooking
        JOIN PHIEUTHUE ON PHIEUDAT.MaBooking=PHIEUTHUE.MaBooking
        JOIN PHONG ON PHIEUTHUE.Maphong=PHONG.Maphong
        JOIN LOAIPHONG ON PHONG.MaLP=LOAIPHONG.MaLP
        JOIN CHITIETPHONGDAT ON PHIEUDAT.MaBooking=CHITIETPHONGDAT.MaBooking
    WHERE DAY(NgayDenDukien)BETWEEN 12 AND 19
        AND MONTH(NgayDenDukien)=12
x
        AND YEAR
(NgayDenDukien)=2022

SELECT *
FROM cau5


exec sp_addlogin NguyenQuocDung, 1234
exec sp_adduser NguyenQuocDung, NguyenQuocDung


CREATE VIEW cau7
AS

    SELECT TOP 3
        KHACHHANG.*,
        SUM(
    CASE 
    WHEN NgayDenDukien=NgayDiDuKien
    THEN 1
    ELSE DAY(NgayDiDuKien)-DAY(NgayDenDukien)
    END
    ) NgayDat
    FROM KHACHHANG
        JOIN PHIEUDAT ON KHACHHANG.MaKH=PHIEUDAT.MaKH
        JOIN PHIEUTHUE ON PHIEUDAT.MaBooking=PHIEUTHUE.MaBooking
        JOIN PHONG ON PHIEUTHUE.Maphong=PHONG.Maphong
        JOIN LOAIPHONG ON PHONG.MaLP=LOAIPHONG.MaLP
    WHERE Kieuphong ='Deluxe Single' OR Kieuphong ='Deluxe Twin'
    GROUP BY KHACHHANG.MaKH,KHACHHANG.TenKH,Diachi,Dienthoai,CCCD,Gioitinh,NgaySinh
    ORDER BY NgayDat DESC

SELECT *
FROM cau7



/*

SELECT * FROM NHANVIEN

SELECT * FROM HOADONTT

SELECT * FROM PHIEUDAT

SELECT * FROM PHIEUTHUE

SELECT * FROM LOAIPHONG

DROP FUNCTION cau3